local ui		= _('UI')
local vr		= _('VR')
local general	= _('General')
local view 		= _('View')

return {
keyCommands = 
{
	-- COCKPIT VIEW FOV / ZOOM PRESETS
	{down = iCommandViewAngleDefault, name = _('Default zoom'), category =  _('View Cockpit absolute FOV')},

	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down =  1.00, name = _('Instant +1.00 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down =  0.95, name = _('Instant +0.95 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down =  0.90, name = _('Instant +0.90 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down =  0.85, name = _('Instant +0.85 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down =  0.80, name = _('Instant +0.80 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down =  0.75, name = _('Instant +0.75 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down =  0.70, name = _('Instant +0.70 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down =  0.65, name = _('Instant +0.65 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down =  0.60, name = _('Instant +0.60 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down =  0.55, name = _('Instant +0.55 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down =  0.50, name = _('Instant +0.50 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down =  0.45, name = _('Instant +0.45 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down =  0.40, name = _('Instant +0.40 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down =  0.35, name = _('Instant +0.35 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down =  0.30, name = _('Instant +0.30 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down =  0.25, name = _('Instant +0.25 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down =  0.20, name = _('Instant +0.20 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down =  0.15, name = _('Instant +0.15 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down =  0.10, name = _('Instant +0.10 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down =  0.00, name = _('Instant  0.00 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down = -0.10, name = _('Instant -0.10 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down = -0.15, name = _('Instant -0.15 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down = -0.20, name = _('Instant -0.20 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down = -0.25, name = _('Instant -0.25 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down = -0.30, name = _('Instant -0.30 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down = -0.35, name = _('Instant -0.35 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down = -0.40, name = _('Instant -0.40 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down = -0.45, name = _('Instant -0.45 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down = -0.50, name = _('Instant -0.50 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down = -0.55, name = _('Instant -0.55 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down = -0.60, name = _('Instant -0.60 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down = -0.65, name = _('Instant -0.65 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down = -0.70, name = _('Instant -0.70 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down = -0.75, name = _('Instant -0.75 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down = -0.80, name = _('Instant -0.80 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down = -0.85, name = _('Instant -0.85 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down = -0.90, name = _('Instant -0.90 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down = -0.95, name = _('Instant -0.95 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down = -1.00, name = _('Instant -1.00 zoom until release'), category =  _('View Cockpit absolute FOV')},

	{down = iCommandViewZoomAbs, value_down =  1.00, name = _('Instant +1.00 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down =  0.95, name = _('Instant +0.95 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down =  0.90, name = _('Instant +0.90 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down =  0.85, name = _('Instant +0.85 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down =  0.80, name = _('Instant +0.80 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down =  0.75, name = _('Instant +0.75 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down =  0.70, name = _('Instant +0.70 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down =  0.65, name = _('Instant +0.65 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down =  0.60, name = _('Instant +0.60 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down =  0.55, name = _('Instant +0.55 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down =  0.50, name = _('Instant +0.50 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down =  0.45, name = _('Instant +0.45 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down =  0.40, name = _('Instant +0.40 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down =  0.35, name = _('Instant +0.35 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down =  0.30, name = _('Instant +0.30 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down =  0.25, name = _('Instant +0.25 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down =  0.20, name = _('Instant +0.20 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down =  0.15, name = _('Instant +0.15 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down =  0.10, name = _('Instant +0.10 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down =  0.00, name = _('Instant  0.00 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down = -0.10, name = _('Instant -0.10 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down = -0.15, name = _('Instant -0.15 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down = -0.20, name = _('Instant -0.20 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down = -0.25, name = _('Instant -0.25 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down = -0.30, name = _('Instant -0.30 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down = -0.35, name = _('Instant -0.35 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down = -0.40, name = _('Instant -0.40 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down = -0.45, name = _('Instant -0.45 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down = -0.50, name = _('Instant -0.50 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down = -0.55, name = _('Instant -0.55 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down = -0.60, name = _('Instant -0.60 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down = -0.65, name = _('Instant -0.65 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down = -0.70, name = _('Instant -0.70 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down = -0.75, name = _('Instant -0.75 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down = -0.80, name = _('Instant -0.80 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down = -0.85, name = _('Instant -0.85 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down = -0.90, name = _('Instant -0.90 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down = -0.95, name = _('Instant -0.95 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down = -1.00, name = _('Instant -1.00 zoom'), category =  _('View Cockpit absolute FOV')},

	{category = vr		, down = iHeadTrackerZoomToggle, value_down = 1.0, name = _('VR Zoom IN')},
	{category = vr		, down = iHeadTrackerZoomToggle, value_down = 0.0, name = _('VR Zoom OUT')},

	{category = vr		, down = iHeadTrackerSpyglassZoomToggle, value_down = 1.0, name = _('VR Spyglass Zoom IN')},
    {category = vr		, down = iHeadTrackerSpyglassZoomToggle, value_down = 0.0, name = _('VR Spyglass Zoom OUT')},


	{combos = {{key = 'Tab'	,									}}	, down = iCommandChat			, name = _('Multiplayer chat - mode All')								, category = general},
	{combos = {{key = 'Tab'	, reformers = {'LCtrl'}				}}	, down = iCommandFriendlyChat	, name = _('Multiplayer chat - mode Allies')							, category = general},
	{combos = {{key = 'Tab'	, reformers = {'LShift'}			}}	, down = iCommandAllChat		, name = _('Chat read/write All')										, category = general},
	{combos = {{key = 'Y'	, reformers = {'LCtrl', 'LShift'}	}}	, down = iCommandChatShowHide	, name = _('Chat show/hide')											, category = general},
	{combos = {{key = 'R'	, reformers = {'LShift'}			}}	, down = iCommandMissionRestart	, name = _('Restart Mission')											, category = general},
	{combos = {{key = '\''	, reformers = {'RAlt'}				}}	, down = iCommandBdaShowHide	, name = _('BDA show/hide')												, category = general},
	-- BDA panel not moved.  remove command
	--{combos = {{key = '\`'  , reformers = {'LCtrl','LAlt'}		}}	, pressed = iCommandBdaShowCursor, up = iCommandBdaShowCursorStop, name = _('BDA show cursor')			, category = general},
	{combos = {{key = 'Tab', reformers = {'LCtrl', 'LShift'} }}, down = iCommandVoiceChat, name = _('Show VoiceChat window'), category = general},
	{down = iCommand_UILayer_MouseLeftButton	, up = iCommand_UILayer_MouseLeftButton		, value_down = 1.0	, value_up = 0.0	, name = _('as left mouse button')		, category = ui},
	{down = iCommand_UILayer_MouseRightButton	, up = iCommand_UILayer_MouseRightButton	, value_down = 1.0	, value_up = 0.0	, name = _('as right mouse button')		, category = ui},
	{down = iCommand_UILayer_MouseWheelFwd		, up = iCommand_UILayer_MouseWheelFwd		, value_down = 1.0	, value_up = 0.0	, name = _('as mouse wheel forward')	, category = ui},
	{down = iCommand_UILayer_MouseWheelBwd		, up = iCommand_UILayer_MouseWheelBwd		, value_down = 1.0	, value_up = 0.0	, name = _('as mouse wheel backward')	, category = ui},
	{down = iCommandPushToTalkEnableVoice		, up = iCommandPushToTalkDisableVoice,		name = _('VoiceChat push-to-talk mic. mode: On/Off voice transfer')				, category = ui},
	{down = iHeadTrackerZoomToggle				, up = iHeadTrackerZoomToggle				, value_down = 1.0	, value_up = 0.0	, name = _('toggle VR Zoom')			, category = vr},
	{down = iHeadTrackerSpyglassZoomToggle		, up = iHeadTrackerSpyglassZoomToggle		, value_down = 1.0	, value_up = 0.0	, name = _('toggle VR Spyglass Zoom')	, category = vr},
	{down = iHeadTrackerPosReset																									, name = _('recenter VR Headset')		, category = vr},

	-- View 
	{combos = {{key = 'C', reformers = {'LShift'}}}, down = iCommandViewCameraToClipboard, name = _('Unload camera position to clipboard'), category = view},
	{combos = {{key = 'V', reformers = {'LShift'}}}, down = iCommandViewClipboardToCamera, name = _('Load camera position from clipboard'), category = view},

	{combos = {{key = 'F9', reformers = {'RCtrl'}}}, down = iCommandViewCatapult, name = _('Aircraft carrier catapult camera'), category = view},
	{combos = {{key = 'F9', reformers = {'RAlt'}}}, down = iCommandViewCatapultCrew, name = _('Aircraft carrier catapult crew camera'), category = view},
	},
}