local ui		= _('UI')
local vr		= _('VR')
local general	= _('General')

return {
keyCommands = 
{
	-- COCKPIT VIEW FOV / ZOOM PRESETS
	{down = iCommandViewAngleDefault, name = _('Default zoom'), category =  _('View Cockpit absolute FOV')},

	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down =  1.00, name = _('Instant +1.00 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down =  0.95, name = _('Instant +0.95 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down =  0.90, name = _('Instant +0.90 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down =  0.85, name = _('Instant +0.85 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down =  0.80, name = _('Instant +0.80 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down =  0.75, name = _('Instant +0.75 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down =  0.70, name = _('Instant +0.70 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down =  0.65, name = _('Instant +0.65 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down =  0.60, name = _('Instant +0.60 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down =  0.55, name = _('Instant +0.55 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down =  0.50, name = _('Instant +0.50 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down =  0.45, name = _('Instant +0.45 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down =  0.40, name = _('Instant +0.40 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down =  0.35, name = _('Instant +0.35 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down =  0.30, name = _('Instant +0.30 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down =  0.25, name = _('Instant +0.25 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down =  0.20, name = _('Instant +0.20 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down =  0.15, name = _('Instant +0.15 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down =  0.10, name = _('Instant +0.10 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down =  0.00, name = _('Instant  0.00 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down = -0.10, name = _('Instant -0.10 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down = -0.15, name = _('Instant -0.15 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down = -0.20, name = _('Instant -0.20 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down = -0.25, name = _('Instant -0.25 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down = -0.30, name = _('Instant -0.30 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down = -0.35, name = _('Instant -0.35 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down = -0.40, name = _('Instant -0.40 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down = -0.45, name = _('Instant -0.45 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down = -0.50, name = _('Instant -0.50 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down = -0.55, name = _('Instant -0.55 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down = -0.60, name = _('Instant -0.60 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down = -0.65, name = _('Instant -0.65 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down = -0.70, name = _('Instant -0.70 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down = -0.75, name = _('Instant -0.75 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down = -0.80, name = _('Instant -0.80 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down = -0.85, name = _('Instant -0.85 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down = -0.90, name = _('Instant -0.90 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down = -0.95, name = _('Instant -0.95 zoom until release'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, up = iCommandViewAngleDefault, value_down = -1.00, name = _('Instant -1.00 zoom until release'), category =  _('View Cockpit absolute FOV')},

	{down = iCommandViewZoomAbs, value_down =  1.00, name = _('Instant +1.00 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down =  0.95, name = _('Instant +0.95 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down =  0.90, name = _('Instant +0.90 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down =  0.85, name = _('Instant +0.85 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down =  0.80, name = _('Instant +0.80 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down =  0.75, name = _('Instant +0.75 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down =  0.70, name = _('Instant +0.70 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down =  0.65, name = _('Instant +0.65 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down =  0.60, name = _('Instant +0.60 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down =  0.55, name = _('Instant +0.55 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down =  0.50, name = _('Instant +0.50 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down =  0.45, name = _('Instant +0.45 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down =  0.40, name = _('Instant +0.40 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down =  0.35, name = _('Instant +0.35 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down =  0.30, name = _('Instant +0.30 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down =  0.25, name = _('Instant +0.25 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down =  0.20, name = _('Instant +0.20 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down =  0.15, name = _('Instant +0.15 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down =  0.10, name = _('Instant +0.10 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down =  0.00, name = _('Instant  0.00 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down = -0.10, name = _('Instant -0.10 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down = -0.15, name = _('Instant -0.15 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down = -0.20, name = _('Instant -0.20 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down = -0.25, name = _('Instant -0.25 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down = -0.30, name = _('Instant -0.30 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down = -0.35, name = _('Instant -0.35 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down = -0.40, name = _('Instant -0.40 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down = -0.45, name = _('Instant -0.45 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down = -0.50, name = _('Instant -0.50 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down = -0.55, name = _('Instant -0.55 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down = -0.60, name = _('Instant -0.60 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down = -0.65, name = _('Instant -0.65 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down = -0.70, name = _('Instant -0.70 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down = -0.75, name = _('Instant -0.75 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down = -0.80, name = _('Instant -0.80 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down = -0.85, name = _('Instant -0.85 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down = -0.90, name = _('Instant -0.90 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down = -0.95, name = _('Instant -0.95 zoom'), category =  _('View Cockpit absolute FOV')},
	{down = iCommandViewZoomAbs, value_down = -1.00, name = _('Instant -1.00 zoom'), category =  _('View Cockpit absolute FOV')},

	{category = vr		, down = iHeadTrackerZoomToggle, value_down = 1.0, name = _('VR Zoom IN')},
	{category = vr		, down = iHeadTrackerZoomToggle, value_down = 0.0, name = _('VR Zoom OUT')},

	{category = vr		, down = iHeadTrackerSpyglassZoomToggle, value_down = 1.0, name = _('VR Spyglass Zoom IN')},
    {category = vr		, down = iHeadTrackerSpyglassZoomToggle, value_down = 0.0, name = _('VR Spyglass Zoom OUT')},

	{category = ui		, down = iCommand_UILayer_MouseLeftButton	, up = iCommand_UILayer_MouseLeftButton		, value_down = 1.0	, value_up = 0.0	, name = _('as left mouse button')},
	{category = ui		, down = iCommand_UILayer_MouseRightButton	, up = iCommand_UILayer_MouseRightButton	, value_down = 1.0	, value_up = 0.0	, name = _('as right mouse button')},
	{category = ui		, down = iCommand_UILayer_MouseWheelFwd		, up = iCommand_UILayer_MouseWheelFwd		, value_down = 1.0	, value_up = 0.0	, name = _('as mouse wheel forward')},
	{category = ui		, down = iCommand_UILayer_MouseWheelBwd		, up = iCommand_UILayer_MouseWheelBwd		, value_down = 1.0	, value_up = 0.0	, name = _('as mouse wheel backward')},
	{category = vr		, down = iHeadTrackerZoomToggle				, up = iHeadTrackerZoomToggle				, value_down = 1.0	, value_up = 0.0	, name = _('toggle VR Zoom')},
    {down = iHeadTrackerSpyglassZoomToggle		, up = iHeadTrackerSpyglassZoomToggle		, value_down = 1.0	, value_up = 0.0	, name = _('toggle VR Spyglass Zoom')	, category = vr},
	{category = vr		, down = iHeadTrackerPosReset																									, name = _('recenter VR Headset')},
	{category = ui		, down = iCommandQuit																											, name = _('as Escape')},

	{category = general	, down = iCommandMissionRestart																									, name = _('Restart Mission')},
	{category = general	, down = iCommandChat																											, name = _('Multiplayer chat - mode All')},
	{category = general	, down = iCommandFriendlyChat																									, name = _('Multiplayer chat - mode Allies')},
	{category = general	, down = iCommandAllChat																										, name = _('Chat read/write All')},
	{category = general	, down = iCommandChatShowHide																									, name = _('Chat show/hide')},
	{category = general	, down = iCommandBdaShowHide																									, name = _('BDA show/hide')},
-- BDA panel not moved.  remove command
--	{category = general	, pressed = iCommandBdaShowCursor				, up = iCommandBdaShowCursorStop			, value_down = 1.0	, value_up = 0.0	, name = _('BDA show cursor')},
	{category = ui	, down = iCommandPushToTalkEnableVoice				, up = iCommandPushToTalkDisableVoice, name = _('VoiceChat push-to-talk mic. mode: On/Off voice transfer')},
},

axisCommands = 
{	
--	{category = vr		, action = iHeadTrackerPitchNormed  , name = _('Head Pitch')},
--	{category = vr		, action = iHeadTrackerYawNormed	, name = _('Head Yaw')},
},
}

